### ISSUE TITLE
Explore protocol buffers vs Avro

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1031]
GA4GH says they are moving to protocol buffers as opposed to Avro due to the streaming rpc support in PB - which is lacking in Avro.   Is this use case, and compatibility with GA4GH, sufficient reason to consider a branch/option of ADAM and bdg that uses PB instead of Avro?

**Comment by fnothaft** [comment]
Since we just rely on Avro for serialization and model definition, we wouldn't benefit from the streaming RPC support. For compatibility, I like the "view" approach that we take, where we translate data from underlying storage format `x` (right now, legacy file formats) to our Avro schemas. From a serialization performance perspective, Avro/Thrift/Protobuf are pretty similar, with Avro being slightly faster IIRC. See [here](https://github.com/eishay/jvm-serializers/wiki) for a longer benchmarking experiment.

Since our long term roadmap is to move to Datasets (where the serialization framework is somewhat moot other than for defining schemas), I'm -0.5 on exploring protobuf.

**Comment by heuermh** [comment]
Close as WontFix?

**Comment by fnothaft** [comment]
Closed as won't fix.
