### ISSUE TITLE
Samtools (htslib)  integration testing

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1120]
Need to add SAM/BAM/VCF round trip integration tests (htslib) to complement existing htsjdk based unit tests.   As motivated by #1104

**Comment by jpdna** [comment]
Wanted to see if anyone has suggestions on three aspects of this before I get going on it:

**1) How should we inform the test suite of where it can find samtools executable?**  
We could  ask that a "SAMTOOLS_HOME" env variable be set and if test suite finds a working samtools there then those tests run, otherwise skipped with a warning output?   Or - the test itself could download a samtools docker container, but then docker is needed.   Method we use needs to work with Jenkins.

2) **Where should the intregration test code should go?**  One idea: `test/scala/org/bdgenomics/adam/rdd/read/SamtoolsSuite.scala` for the sam/bam

3) I**s it an ok  approach to extend `ADAMFunSuite`** for these samtools intergration tests just as we do for all the unit test suites?

**Comment by fnothaft** [comment]
Going out of order:

> 3) Is it an ok approach to extend ADAMFunSuite for these samtools intergration tests just as we do for all the unit test suites?

That sounds good to me!

> 1) How should we inform the test suite of where it can find samtools executable?
>
> We could ask that a "SAMTOOLS_HOME" env variable be set and if test suite finds a working samtools there then those tests run, otherwise skipped with a warning output? Or - the test itself could download a samtools docker container, but then docker is needed. Method we use needs to work with Jenkins.

We'll want to tag all of these tests with some sort of an [integration test tag](http://www.scalatest.org/user_guide/tagging_your_tests). That said, I think that requiring Docker for the integration tests is A-OK. We'll be the main consumers of the integration test suite.

We'll also need to create a repo with integration test files, because these should be real life sized inputs.

> 2) Where should the intregration test code should go? One idea: test/scala/org/bdgenomics/adam/rdd/read/SamtoolsSuite.scala for the sam/bam

I would probably put them in an `org.bdgenomics.adam.integration` package. This one would probably fit best in `org.bdgenomics.adam.cli.integration`, actually.

**Comment by fnothaft** [comment]
Closing this in favor of #1407.
