### ISSUE TITLE
Clean up packaging of conversion methods

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1170]
Continued from #1157. We should:
- Do a review pass and make some of the `AlignmentRecordConverter` methods private
- Make `SAMFileHeaderWritable` private to ADAM, and change the `AlignmentRecordConverter.convert` signature to take a `SAMFileHeader`

Also, contributed for discussion by @heuermh:

> > Also, I think it's more useful to have the conversion utility at the record level, rather than the RDD level, since then it can be used outside Spark.
> 
> If that were the case, it would be preferable to me to have the conversion stuff written in Java instead of Scala and be a library external to ADAM.

**Comment by heuermh** [comment]
A proposal for said external java library here:
https://github.com/heuermh/bdg-convert

It is inspired by [Commons Convert](https://commons.apache.org/sandbox/commons-convert) but uses [Guice](https://github.com/google/guice) instead of a custom registry.  Then I like the concept of htsjdk's `ValidationStringency` but don't like the name.  Please propose something better (and shorter) than `ConversionStringency`.

**Comment by heuermh** [comment]
I've started fleshing out conversions from Biojava and my own dishevelled library, here in a separate repo due to LGPL licensing of the dependencies:
https://github.com/heuermh/dishevelled-bio/tree/master/convert

It also depends on the bdg-formats Sequence/Slice/Read pull request, so won't build without the right snapshot dependency.

I think there is enough in the bdg-convert repo and here to demonstrate the proposal.

**Comment by heuermh** [comment]
Split the external library proposal into a separate issue #1197 for further discussion.  Let's keep this issue focused on the two visibility items mentioned above.

**Comment by fnothaft** [comment]
I'm triaging this to 0.24.0.
