### ISSUE TITLE
MDTagging fails on GRCh38

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1192]
I was running the `transform -add_md_tags` code on GRCh38, and was getting contig name mismatches that caused failures. It looked like a header parsing problem. TBD. I need to look back in the logs for the stack trace.

**Comment by heuermh** [comment]
@fnothaft thinking about cutting a 0.20.0 release sooner rather than later, would this need to go?

**Comment by fnothaft** [comment]
Yeah, from inspection, I've found that this isn't "MD tagging is borked", but rather it is "loading the GRCh38 FASTA is borked", which is IMO a showstopper.

**Comment by fnothaft** [comment]
I'm hoping to have a PR today or tomorrow.

**Comment by heuermh** [comment]
Mind if I add a new 0.22 milestone, rework the 0.20 and 0.21 milestones, and prepare for a 0.20.0 release on Monday Oct 10th?

**Comment by fnothaft** [comment]
@heuermh What would get kicked from 0.20.0 to 0.21.0? The variant refactoring? Otherwise, I'd reallllly like to get the pipe stuff in to 0.20.0, as well as this.

**Comment by fnothaft** [comment]
What would the timing be for 0.20.0, 0.21.0, etc?

**Comment by heuermh** [comment]
I'd bump everything but this to 0.21. I'm not sure I have bandwidth to fully test the pipe API stuff by Monday, since SnpEff is perhaps not the best first thing to try, given the variant annotation refactor is still incomplete. Have other uses for the pipe API in mind?

For dates I'd propose Oct 10th for 0.20.0, Dec 10th for 0.21, and sometime in 2017 for 0.22.

**Comment by fnothaft** [comment]
> Have other uses for the pipe API in mind?

Yes, I'm rewriting https://github.com/bigdatagenomics/snappea using the pipe API and need a stable release with the pipe API before December.
