### ISSUE TITLE
Support for INSDC Sequence records (i.e., Genbank/EMBL format)?

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#1219]
Any thoughts about supporting the INSDC data model as well?  This would be for the data in genbank/embl format.  This corresponds to the `SeqRecord` data type in biopython.  Apologies if this questions is totally redundant/annoying.

**Comment by fnothaft** [comment]
I think that'd map well to @heuermh's https://github.com/bigdatagenomics/bdg-formats/pull/83, no? If so, SGTM!

**Comment by laserson** [comment]
Yes, but it would extend a ways past it.  What @heuermh currently implemented is similar to Biopython's `Seq` object.  The `SeqRecord` object includes one of those, but also includes per-letter annotations (e.g., quality scores), dbxrefs, and a list of `Feature` objects.  Basically, the sequence and all the annotations on top of it.  Is there any appetite to develop that?

**Comment by fnothaft** [comment]
Oh, that's kinda cool. I might say that we could add the per-base annotations and the dbxrefs, but I would leave out the Features, since we can reconstruct that from a join. @heuermh thoughts?

**Comment by heuermh** [comment]
I was thinking `Sequence` and `Feature` as currently defined, and then a `SequenceAnnotation` or similar for the list of features and other stuff that goes in a Biopython `SeqRecord` or Biojava `RichSequence`.  Didn't the GA4GH recently propose something for this?

**Comment by fnothaft** [comment]
Nice! I like that proposal.

**Comment by heuermh** [comment]
@laserson What would you like to use as the specification/reference model for this?

I've written Biojava 1.x ([biojava-legacy](https://github.com/biojava/biojava-legacy)) to/from `Sequence/Slice/Read` conversions [here](https://github.com/heuermh/dishevelled-bio/tree/master/convert/src/main/java/org/dishevelled/bio/convert/biojava), similar could be done for Biojava 5.x on HEAD ([biojava](https://github.com/biojava/biojava)), and it wouldn't take much to use those libraries to support Genbank/EMBL formats in addition to FASTA and FASTQ.

Since Biojava is LGPL version 2.1, there is a question of where this code should live.  There is also a question of the proposal at https://github.com/bigdatagenomics/bdg-convert.

**Comment by laserson** [comment]
I don't have experience with Biojava but probably a good place to start?

**Comment by heuermh** [comment]
A good place to start, sure, but some of the code is 15 years old.  Is there a more up-to-date specification or reference?

There's this for the feature table
http://www.insdc.org/files/feature_table.html

and an annotated example Genbank record
https://www.ncbi.nlm.nih.gov/genbank/samplerecord/

I think I'm with Chris Fields in that, well, good luck
https://www.biostars.org/p/165727/

Given a Genbank record, which bits would be important to you?

**Comment by laserson** [comment]
Yeah, I'm also aware of how unspecified the Genbank format is.

For me, the obvious things to add are Features on top of the sequence.  Also nice would be the per-letter annotations.  And also the ket-value pairs you can add (is this called "qualifiers" or something like that?)

**Comment by heuermh** [comment]
Fixed by https://github.com/heuermh/biojava-adam, which is in the process of being transferred to the Biojava organization.
