### ISSUE TITLE
Need to support BCF output format

### ISSUE THREAD

**Issue by nealsid** [bigdatagenomics/adam#153]
Frank sketched out a possible implementation in PR 151:

RE: VCF vs. BCF support; I believe that if we want to add BCF support, we could add a setFormat option to the ADAMVCFOutputFormat object, and then do a getFormat call in the superclass constructor.

**Comment by heuermh** [comment]
Fixed by #1060, caveat lack of support for BCF v2.2 in htsjdk:

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala#L180
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala#L186
