### ISSUE TITLE
Genomics Pipeline

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1724]
Hi,
I am working currently in a project on building genomics pipeline.  Requirement is something like this-

I will get the Input (.fastq file). And needs to run this steps:
1. Alignment with the sequence genome
2. Conversion .fastq to .adam
3. Sorting 
4. Duplicate removal
5.Base callibration
6.Analysis Ready Reads
7. Variant calling(SNP, INDEL)
8. Variant Filtering
9. Variant Annotation

My question is : Is there any way I can run a automate script , so that when I  put the .fastq data, the whole process will run automatically

Thanks!

**Comment by heuermh** [comment]
Sorry for not replying sooner.

ADAM is more a framework or library on which to build workflows rather than something that runs an entire pipeline.  For a full variant calling workflow as you describe above, I would suggest using BWA via Cannoli for alignment, ADAM for preprocessing, freebayes via Cannoli or avocado for variant calling, ADAM for variant filtering, and SnpEff via Cannoli for variant annotation.

https://github.com/bigdatagenomics/cannoli
https://github.com/bigdatagenomics/avocado

For running such a workflow, you'd want something like Toil or Nextflow.

https://github.com/BD2KGenomics/toil
https://www.nextflow.io

We're building out such Toil-based workflows in this repository

https://github.com/bigdatagenomics/workflows

**Comment by Rokshan2016** [comment]
ok, will check that

Thanks
