### ISSUE TITLE
suffix arrays implementation

### ISSUE THREAD

**Issue by antonkulaga** [bigdatagenomics/adam#1872]
Searching for repeats as well as specific strings inside large genomes is quite common.Having a suffix array data structure will be very helpful for many use cases

**Comment by fnothaft** [comment]
I'm hesitant to take this on in ADAM, since we don't have code that builds a suffix array. That said, I'd be open to do it if someone has suffix array building code (ping @ryan-williams). What's the specific query pattern you have? A small set of sequences against a lot of reads (i.e., could be run map-side, should be sufficient for the repeat search use case) or reads vs. reads (e.g., de novo assemby)?

**Comment by heuermh** [comment]
Hello @antonkulaga, is this still something you'd like to see?  I'm also curious about your use cases.

**Comment by heuermh** [comment]
Closing as WontFix
