### ISSUE TITLE
Indel realignment discards all unmapped reads

### ISSUE THREAD

**Issue by pauldwolfe** [bigdatagenomics/adam#2018]
Presumably as a performance improvement the first step in indel realignment is to filter out all unmapped reads. While this makes sense in a lot of cases, we would like to ensure that we don't drop any reads at any point in our pipeline marked or not.

This change will introduce optionality to not discard any reads in indel realignment.

**Comment by pauldwolfe** [comment]
Duplicate of #2019

**Comment by heuermh** [comment]
Hello @pauldwolfe, thanks for the contribution!

The workflow in Big Data Genomics is typically:

 - Create an issue describing a bug, enhancement, or feature request
 - Create a pull request for that issue
 - Add `Fixes #issuenumber` in the pull request description to establish link to issue
 - Add `[PROJECT-ISSUENUMBER]` prefix to pull request name (Note our [contributing docs](https://github.com/bigdatagenomics/adam/blob/master/CONTRIBUTING.md) say to add the same prefix to the commit message, but I don't usually do that)
 - Issues and pull requests are triaged to release version milestones
 - Github adds Jenkins CI and other check reports to pull request
 - Pull request is reviewed by one or more contributors
 - Pull request is merged by a contributor other than the one submitting the pull request
 - When pull request is merged, Github automagically closes the linked issue

I reopened this issue so that it might be closed when pull request #2019 is merged.

**Comment by heuermh** [comment]
Closing as WontFix
