### ISSUE TITLE
loadFastaDna does not seem to work

### ISSUE THREAD

**Issue by antonkulaga** [bigdatagenomics/adam#2182]
loadFastaDna does not seem to work in 0.28.0
```
val genome = sc.loadFastaDna("file:///data/ensembl/96/species/homo_sapiens/Homo_sapiens.GRCh38.dna.primary_assembly.fa")
```
gives:
```
 org.bdgenomics.adam.rdd.sequence.SequenceDataset = RDDBoundSequenceDataset with 0 reference sequences
```
To reproduce it is enough to download primary Human assembly from Ensembl and to open it

**Comment by heuermh** [comment]
By not work, do you mean that there are `0 reference sequences`?  The dataset should be full of sequence records.

As discussed before in https://github.com/bigdatagenomics/adam/issues/1894, the sequence dictionary is not created on the fly any more.  If you need the sequence dictionary, either call `genome.createSequenceDictionary()` after load

```scala
val sequences = sc.loadFastaDna("foo.fa.gz").createSequenceDictionary()
```

or load a sequence dictionary separately from a `.dict` or `.genome` file and provide it to the `SequenceDataset`

```scala
val sd = sc.loadSequenceDictionary("foo.dict");
val sequences = sc.loadFastaDna("foo.fa.gz").replaceSequences(sd)
```

(Now that we have `SequenceDataset`, the SequenceDictionary field is confusingly named, see https://github.com/bigdatagenomics/adam/issues/2171)

Also note that you'll probably want to use `SliceDataset` instead of `SequenceDataset` for loading the Ensembl primary assembly.  `Slice` is most similar to `NucleotideContigFragment` from before; `Sequence` records include the entire sequence in a single record.

```scala
val slices = sc.loadFastaDna("foo.fa.gz", maximumLength = 10000L)
```

Hope this helps.
