### ISSUE TITLE
adam-submit: Not able to transform fasta file to adam format.

### ISSUE THREAD

**Issue by shashwatwork** [bigdatagenomics/adam#2288]
I tried running adam-submit on AWS EMR in order to convert fasta genomic sequence file to adam but no transformation has been applied. Following commands have been used - 

> adam-submit --fasta2adam s3://gendata/cov2.fasta s3://gendata/cov2.adam
> adam-submit --fasta2adam cov2.fasta cov2.adam
> adam-submit --transformAlignments s3://gendata/cov2.fasta s3://gendata/cov2.adam

Please let me know if I am making any errors in running the above commands or any additional args required.

![Output](https://user-images.githubusercontent.com/22785727/103645131-8709ba00-4f7d-11eb-8266-399470a64abf.png)

**Comment by heuermh** [comment]
Hello @shashwatwork, thanks for submitting this issue!

First, based on the list of ADAM commands in the screenshot, you are running a very old version of ADAM.  You may wish to update to a more recent version, see https://github.com/bigdatagenomics/adam/releases

Second, the format of your command line is a bit off, it should be
```bash
adam-submit fasta2adam s3://gendata/cov2.fasta s3://gendata/cov2.adam
adam-submit fasta2adam cov2.fasta cov2.adam
adam-submit transformAlignments s3://gendata/cov2.fasta s3://gendata/cov2.adam
```
instead of what you have above.

Hope this helps!

**Comment by shashwatwork** [comment]
Thnx, a bunch @heuermh updated adam to a recent version and modified cmd line args based on your suggestions that worked.

**Comment by heuermh** [comment]
Good to hear!
