### ISSUE TITLE
Simplify `ADAMContext`

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#553]
I am finding `ADAMContext` to be more complicated than I'd like, especially when I am thinking about the Python API and the `JavaADAMContext`.  Here are a few questions:

* What is the purpose of `adamLoad`?  We only have a relatively small number of types.  Does it make sense to break `adamLoad` out to the non-generic cases we are interested in?  We already have a `loadAlignments` function.

* What is the purpose of `adamDictionaryLoad`?  It looks like it's basically an agg on an `RDD[AlignmentRecord]`.  Why don't we have the user load the RDD themselves, and then have a function `RDD[AlignmentRecord] => SequenceDictionary`?  If the use wants to do it on a `.bam` file, she can use `adamBamDictionaryLoad`.

* What is the purpose of `maybeLoadBam`?  Make the user check that the file has the proper extension.  How is it useful to return an `Option`?

* What's the purpose of `FeaturesContext`?  It just adds some loading functions.  Could be moved to `ADAMContext`.  Same with `VariationContext`.

* What's the purpose of `GeneContext`?  Seems simpler to implement it by loading GTF `Feature` objects and then transforming the `RDD[Feature]` to `RDD[Gene]`.  Actually, this is what it does, but the implicit pimp-my-lib architecture just seems more confusing.

* `VariantContext` is named strangely as well.

* It's be great to consolidate some of the `*RDDFunctions` whenever possible, though not as obvious to me yet exactly what/how.

A lot of this automagically calling functions by looking at extensions seems like over-complication, and not really that useful.  How often will it happen that the user doesn't know whether they're loading data from a `.bam` file or an `.adam` file?

Why are there so many `*Context` objects?

Thoughts on cleanup/simplification?

**Comment by ryan-williams** [comment]
I was probably the last person mucking around in some of the `*load` functions, and was mostly trying to make them more specific to the underlying data types that any user calling them should **know** they are loading, as you describe, so I support the spirit behind most of what you're proposing.

`maybeLoadBam` is [only used in one place](https://github.com/bigdatagenomics/adam/blob/936bb8a2e1fd911074d1d1c15a85bd039f7f2bcd/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L309) and should probably be made private; likewise `maybeLoadFastq`.

I don't think the basic pattern they represent ("load alignments from a BAM iff the file is a `.bam`, otherwise return `None` so that the next file-extension-specific method can take a look") is unreasonable given the underlying problem that `loadAlignments` faces (it may need to read from one of three different formats, each requiring different logic), but I'm open to suggestions on alternative ways to implement that logic.

**Comment by fnothaft** [comment]
This is partially my fault. I split ADAMContext up in #356, to clean up several other issues. That being said, I do think that we should eliminate as much from the `*Context`s as is possible.

> * What is the purpose of adamLoad? We only have a relatively small number of types. Does it make sense to break adamLoad out to the non-generic cases we are interested in? We already have a loadAlignments function.

I'm a big fan of this; @erictu's #542 extended @ryan-williams #468 to genotypes, and I think that's the correct way to go for the other data types as well.

> * What is the purpose of adamDictionaryLoad? It looks like it's basically an agg on an RDD[AlignmentRecord]. Why don't we have the user load the RDD themselves, and then have a function RDD[AlignmentRecord] => SequenceDictionary? If the use wants to do it on a .bam file, she can use adamBamDictionaryLoad.

We do have a function that goes `RDD[AlignmentRecord] => SequenceDictionary`; I agree RE: nixing that.

> * What is the purpose of maybeLoadBam? Make the user check that the file has the proper extension. How is it useful to return an Option?

Just merged #554, so no longer an issue! Thanks @ryan-williams! I'll fix `maybeLoadVcf` in a second.

> * What's the purpose of FeaturesContext? It just adds some loading functions. Could be moved to ADAMContext. Same with VariationContext.

+1; can we roll all the ADAMContext's together?

> * What's the purpose of GeneContext? Seems simpler to implement it by loading GTF Feature objects and then transforming the RDD[Feature] to RDD[Gene]. Actually, this is what it does, but the implicit pimp-my-lib architecture just seems more confusing.

Shouldn't that be in `FeatureContext` anyways (if one exists)? I don't have a strong feeling here.

> * VariantContext is named strangely as well.

Ah, yeah, that's a legacy thing. Originally, the name mirrored the Picard `VariantContext`. I'd be down with changing it.

> * It's be great to consolidate some of the *RDDFunctions whenever possible, though not as obvious to me yet exactly what/how.

So, you can't really consolidate them down into a single class, because they all take different constructors and have different types. We used to have them in a single file; I didn't love that myself, TBH.

**Comment by massie** [comment]
+1 to rolling all the *Contexts into a single ADAMContext.

**Comment by fnothaft** [comment]
If no one is working on this, I'll take it.

**Comment by laserson** [comment]
Yeah, it was a bit obnoxious for me to file this without having a PR in process. I won't get to this till next week at the earliest, so feel free to hit it if you want.  Otherwise, I'll work on it then.

**Comment by fnothaft** [comment]
Oh, I don't think it's obnoxious! For something that's _somewhat_ big like this, I think it'd be a bad idea to start doing the work without discussing it first.

BTW, I am going to base this off of https://github.com/bigdatagenomics/adam/pull/478 to minimize future rebase conflicts.

**Comment by fnothaft** [comment]
Also, there are a few `*Context`s that are purely package private. I'm going to leave these, unless anyone  objects.

**Comment by laserson** [comment]
Well, one of the main issues I'd like to address in this issue is not just to simplify the user-facing public API, but also to simplify the developer-facing private API. So I still vote to get rid of as much as possible.

**Comment by fnothaft** [comment]
@laserson OK. I'm going to clean the public facing API first, and see how far that gets us. It's easy to do more cutting if necessary.

**Comment by fnothaft** [comment]
Closed by #567.
