### ISSUE TITLE
Adam2Fastq should be merged into Transform

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#566]
It looks like this should be really straightforward to do.

**Comment by ryan-williams** [comment]
IIRC, I added it outside of transform because I wanted it to support a default understanding of what one vs. two command-line arguments would mean (interleaved vs. paired fastq files) that was inconsistent or too messy to try to unify with the assumptions in `transform`. 

Not sure if that's changed or there's a way around it or it doesn't seem important.

**Comment by fnothaft** [comment]
Ah, sure! Makes sense. Thanks for the comment @ryan-williams; I'll close this.
