### ISSUE TITLE
BQSR should support recalibration across multiple ADAM files

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#58]
Per the discussion here: https://github.com/bigdatagenomics/adam/pull/48#issuecomment-32917211

It doesn't appear that BQSR could currently be (correctly) run across multiple ADAM files with overlapping read groups (or possibly multiple ADAM files with different read groups either, I'm not sure).  

We should probably (a) make that clearer in the documentation to BQSR, and (b) correct it (by building or maintaining a master read-group map that can be used to correctly define the read group covariate across files).

**Comment by fnothaft** [comment]
Closing as won't fix. The current BQSR codebase does support BQSR over a union of RDDs, which is generally sufficient for this issue, but also, we don't recommend running multi-sample BQSR. It's not that we recommend against it, but rather there's no benefit to running multi-sample BQSR instead of single-sample BQSR due to how the recalibration model is trained.
