### ISSUE TITLE
Improve error message when we can't find a ReferenceRegion for a contig

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#582]
Seen on the [mailing list](https://groups.google.com/forum/#!topic/adam-developers/lgkvNbxrrK0). If calling `ReferenceRegion(contig: NucleotideContigFragment)` returns `None`, we throw a nondescript error.

**Comment by InvisibleTech** [comment]
Is this issue still open?  I was looking for a starting  point to help out and noticed this issue has an assignee but was also labeled "pick me up".

**Comment by heuermh** [comment]
@InvisibleTech go for it!  We're not too strict about the Assignee label.

**Comment by InvisibleTech** [comment]
Requirements question.   I am looking at fixing this issue with some defensive coding in:

> org.bdgenomics.adam.converters.FragmentCollector#apply
Normally in a Java world I would do something like throw a RuntimeException like IllegalArgumentException but I am not sure in FP Scala land if this is legit.  

Looking at the code in:

> org.bdgenomics.adam.models.ReferenceRegion#apply

I see that if any of the following referenced fields aren't valued we would get None because of the generators used in the for-comprehension:

>       contig <- Option(fragment.getContig)
>       contigName <- Option(contig.getContigName)
>       startPosition <- Option(fragment.getFragmentStartPosition)
> 

So which of these fields is required to properly create a ReferenceRegion?  Is this an error or is it more legit for me to silently create some empty Seq[(ReferenceRegion, String)] if ReferenceRegion(fragment) produces a None?
