### ISSUE TITLE
Delete bam2adam

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#674]
Seems people occasionally run into problems on the mailing list with `bam2adam` and we generally tell them to use `transform` instead.  Thoughts?

**Comment by massie** [comment]
The `bam2adam` command was created as a backup to the `transform` command since occasionally Hadoop-BAM would fail to properly split a BAM on HDFS. The `bam2adam` command only works on local BAM files so there's no split processing. We should keep the functionality in ADAM but hide the command away. For example, remove it from the help menu.

**Comment by fnothaft** [comment]
I am +1 removing `bam2adam`. Within the past year, we have not had a `transform` related issue that was resolved by moving to `bam2adam`.
