### ISSUE TITLE
Remove, or add documentation to, FeatureHierarchy

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#709]
I stumbled across [this](https://github.com/bigdatagenomics/adam/blob/a94b9c98e314eb1d424859b504b76527df73a97c/adam-core/src/main/scala/org/bdgenomics/adam/models/FeatureHierarchy.scala) today; what is it, why is it here? It appears unused.

I'm open to variations on what I imagine it is supposed to do, but it seems like it might have been an idea that was abandoned, in which case I'll remove it. Can anyone provide context?

**Comment by fnothaft** [comment]
CC @tdanford @laserson

**Comment by laserson** [comment]
I think this is a remnant of an early "feature" proposal that would provide familiar interfaces for `Feature` objects that were similar to their sources.  I don't think I've used it myself, and your reporting this issue is making me think it's not used anywhere in the codebase, so I'm fine with nixing it.

**Comment by fnothaft** [comment]
I would be +1 towards removing it.

**Comment by fnothaft** [comment]
Closed by #728.
