### ISSUE TITLE
Allow Variant to ReferenceRegion conversion

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/adam#768]
Right now there is no conversion from `Variant` to `ReferenceRegion`.  This would be needed to perform a `RegionJoin` with an RDD of `Variants`.  I can add this, but wanted to make sure I wasn't missing in anything, or if there some relationship between `Feature` and `Variant` that would take care of this.

**Comment by fnothaft** [comment]
I see that we have one for `Variant` to `ReferencePosition`: https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/models/VariantContext.scala#L49

Since `ReferencePosition` extends `ReferenceRegion`, you could use that for a region join. That being said, the `Variant -> ReferencePosition` mapping assumes all variants are point variants, which isn't the best. Perhaps that is something that should be refactored?
