### ISSUE TITLE
How do we handle reads that don't have original quality scores when converting to FASTQ with original qualities?

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#818]
In https://github.com/bigdatagenomics/adam/pull/745 we added the ability to convert X->FASTQ where the original base qualities are written out. Right now, if the base qualities aren't defined, this will throw a NPE. There are several alternatives:

* Throw a better exception (IllegalArgument?)
* Write `*` quality string
* Write the values from `qual` instead.

**Comment by arahuja** [comment]
From the discussion #815 and looking at the code, it looks like a NPE _won't_ be thrown, which is the worst of all cases, and instead we are doing `3` from above 

My vote would be `IllegalArgument`, I think, though I imagine I want to be configurable.  2 use cases I see are generating the original fastqs (would want an error than if this isn't possible) or just generating some fastqs with the most original scores possible (would want to replace the scores with whatever was available?

If we put in the '*' there should be somewhat sort of warning logged at least otherwise you might end up with unexpected data  (says the person who wrote the thing that gives unexpected data)

**Comment by fnothaft** [comment]
Oops! Misread the code. I agree with you around configuration. We could use the [validation strictness flags](https://samtools.github.io/htsjdk/javadoc/htsjdk/). strict could map to an IAE, and and lenient could make to whatever is available and log a warning.

**Comment by heuermh** [comment]
See pull request #856

**Comment by fnothaft** [comment]
Resolved by #856.
