### ISSUE TITLE
Add "file" command for reading multiple ADAM command-lines from a file and running them in sequence

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#833]
I had this idea yesterday while thinking about ways to extend #832, and I think it will be a simple and powerful abstraction to expose in the ADAM CLI.

My immediate impetus is that I have a directory with many pairs of `.fastq` files that I want converted to ADAM.

There's not an obvious way to tell e.g. `transform`: "find all pairs of files of that end with `_1.fastq` vs. `_2.fastq`, and send them in pairs through the `transform` cmd a la #831", nor should there be, probably. Instead, I can generate the commands I want via some shell commands, and then pass them as a file to ADAM.

**Comment by heuermh** [comment]
Honestly I'm not that in favor of this issue or #832 for that matter.  These kind of tasks seem more well suited for a system outside of ADAM.

**Comment by laserson** [comment]
Not sure I understand.  If you generate the commands in a shell script, can't you also execute them from the shell script?

**Comment by ryan-williams** [comment]
@heuermh OK, I'm interested to hear more about how/whether you think these kinds of tasks should be done.

Given: I have a large, nested directory-hierarchy of `.bam` files, all of which I'd like to convert to ADAM before performing further analyses on them.

1. Is this not a use case we want to support?
2. Is there a way of performing this conversion more easily?

@laserson: fair question. Running many (I'm about to do this for a couple hundred pairs of fastq's) sequential `adam-submit` commands from a shell incurs nontrivial overhead starting up and tearing down Spark apps, and the work is logically one application to me (e.g. I'd like to follow its progress on one Spark-web-UI application page rather than across 100s).

**Comment by heuermh** [comment]
I guess the use case feels not-quite-right to me.  In my experience analyses were done with many steps per sample rather than one step at a time for a bunch of input files.  In your example, what will be downstream of the conversion step?

I show an example of using a workflow tool + docker here https://github.com/heuermh/bdg-nextflow which does incur the overhead you describe above.

If one were to set up a Spark cluster and use an ADAM context pointing to that cluster in the workflow (e.g. ```--master spark://1.2.3.4:7077 --deploy-mode cluster ...```), I believe that might solve the overhead problem.  Job management would be provided by the workflow tool (e.g. [Nextflow](http://www.nextflow.io/), [Toil](https://github.com/BD2KGenomics/toil), something otherwise [CWL-compliant](https://github.com/common-workflow-language/common-workflow-language#participating-organizations), etc.) and job scheduling on Spark would be provided by whichever technology the Spark cluster is using (e.g. Mesos, YARN, etc.).

**Comment by ryan-williams** [comment]
OK, having played with this more over the weekend I'm more sympathetic to solving the "many ADAM apps, ideally in parallel" problem at a different part of the stack, e.g. letting the YARN scheduler manage all the jobs I can throw at it. 

So far using YARN for this has worked well / as intended for modest numbers of apps, but kind of falls over once I start to saturate the cluster's resources (i.e. isn't really managing queued container requests gracefully), but that's not ADAM's problem.

So I'll close this, thanks for the discussion @heuermh @laserson.
