### ISSUE TITLE
Target Spark 1.5.2 as default Spark version

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#911]
Or alternatively, Spark 1.6.0. I don't have a strong opinion, but I feel like we've validated more on Spark 1.5.2.

**Comment by heuermh** [comment]
Want to default to Hadoop 2.6.0 or later at the same time?

**Comment by fnothaft** [comment]
Yes, Hadoop 2.6.0 probably. Good call.

**Comment by NeillGibson** [comment]
Hi,

Moving to Spark 1.6 would have the benefit that you can migrate the library to use the DataSet API.
But its probably wise to first see how stable the DataSets API is and the uptake of Spark 1.6.

I am not sure if it's worth moving to the DataFrame API in Spark 1.5.2. Since the DataFrame API is incompatibly with some transformations /code in this library. And you would need to support versions of Adam / Spark for the RDD, DataFrame and DataSet API. 
https://github.com/bigdatagenomics/adam/issues/912

Spark 1.5.2 is now widely used but I guess people will move fast to  Spark 1.6 if the DataSet API turns out to work / be stable?

![Spark version usage](https://databricks.com/wp-content/uploads/2016/01/spark-version-trend-final-1024x512.png)
https://databricks.com/blog/2016/01/05/spark-2015-year-in-review.html

**Comment by heuermh** [comment]
Closed by #932
