### ISSUE TITLE
Expose sorting by reference index

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#952]
See https://github.com/bigdatagenomics/adam/issues/823; we don't currently expose sorting by index on the CLI, though.

**Comment by heuermh** [comment]
Can this be pushed off to 0.20.0?

**Comment by fnothaft** [comment]
@heuermh or @jpdna, can one of you take this? It should be straightforward, let's discuss on the call today.

**Comment by jpdna** [comment]
This does interests me giving my general interest in sorting/index type stuff.  I'm happy to take it unless someone else wants to.

**Comment by fnothaft** [comment]
Thanks @jpdna! I've assigned it to you.

**Comment by jpdna** [comment]
As I interpret it, the goal of this issue is to add a CLI option flag `--sort_orig_ref_order` to be included when running `ADAM2Vcf` or  when outputting a  sam/bam file using  `transform`

The result would be a vcf or sam/bam file with records  sorted first by the referenceIndex of the contig, and then by genomic position.   The header sequence dictionary rows will also match the referenceIndex ordering.

Is this correct?

**Question:** I am not clear as to whether indeed we do wish for this command to also sort by genomic position within the reference/contig groups.  It is possible the original sam/bam or vcf was not sorted by position, however we have no way to recover the original order, and there is not a guarantee the order ADAM would output would be the same as the original vcf or bam.

Also - I need to look at code to understand more about the cases where 
a) the contigs came in lex sorted, but don't appear in the original header
b) the contigs header metadata is present, defining a sort order but its not lexographic
c) contigs come in grouped by records, but not lexographically, and no header

As long a SequenceDictionary exists with contigs with referenceIndex, I guess the above a,b,c is upstream from concern in this issue, but just wanted to check.

**Comment by fnothaft** [comment]
I have this implemented, just working on unit tests, will PR tomorrow.
